bug-fix-test/catalog-test
ekaterinabeidel/JavaBrightBrains pull request #15
Opened 2024-11-08 23:18 UTC by ivanbeidel

2024-11-09 09:14 UTC, ZhuravlevaS commented on src/main/java/bookstore/javabrightbrains/handler/ResponseExceptionHandler.java
> +    public ResponseEntity<Map<String, String>> handleValidationExceptions(MethodArgumentNotValidException ex) {
А где ты используешь этот эксепшен?

2024-11-10 12:19 UTC, ZhuravlevaS requested changes

2024-11-10 12:19 UTC, ZhuravlevaS commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
А версия тут точно не нужна?

2024-11-10 12:19 UTC, ZhuravlevaS commented on src/main/java/bookstore/javabrightbrains/entity/Book.java
> +    public Book(String title, String author, String description, BigDecimal price, int discount, Long categoryId, int totalStock, String imageLink) {
есть аннтация @AllArgsConstructor, конструктор точно нужен?

2024-11-10 12:19 UTC, ZhuravlevaS commented on src/main/java/bookstore/javabrightbrains/entity/Favorite.java
> +    public Favorite(User user, Book book) {
тут тоже есть аннтоция

2024-11-10 12:19 UTC, ZhuravlevaS commented on src/main/java/bookstore/javabrightbrains/entity/User.java
> +    public User(Long id) {
?

2024-11-10 12:19 UTC, ZhuravlevaS commented on src/test/java/bookstore/javabrightbrains/controller/BookAdminControllerTest.java
> +        Favorite favorite = favoriteRepository.save(new Favorite(new User(1L), book));
у нас есть сгенерированные Favorite в схеме, тебе точно нужно еще создавать?

2024-11-10 23:12 UTC, ekaterinabeidel commented on src/main/java/bookstore/javabrightbrains/handler/ResponseExceptionHandler.java
> +    public ResponseEntity<Map<String, String>> handleValidationExceptions(MethodArgumentNotValidException ex) {
для валидации полей в дто, спринг его сам использует

2024-11-10 23:27 UTC, ekaterinabeidel requested changes

2024-11-12 11:29 UTC, ekaterinabeidel approved these changes

2024-11-12 11:35 UTC, merged